import { Link } from 'react-router-dom';
import { Zap, Brain, Target, BarChart3, MessageSquare, FileText, Building2, ChevronRight, Star, CheckCircle } from 'lucide-react';

const features = [
  { icon: FileText, title: 'Resume Analyzer', desc: 'AI extracts skills, projects, and experience from your PDF resume with pinpoint accuracy.', color: 'var(--accent-blue)' },
  { icon: Target, title: 'ATS Score Engine', desc: 'Compare your resume against any job description. Know your match score before applying.', color: 'var(--accent-green)' },
  { icon: Brain, title: 'Skill Gap Analysis', desc: 'Identify exactly which skills you\'re missing and get a personalized 4-week learning roadmap.', color: 'var(--accent-purple)' },
  { icon: MessageSquare, title: 'AI Mock Interviews', desc: 'Personalized questions based on your resume, role, and target company. Evaluated by Gemini AI.', color: 'var(--accent-cyan)' },
  { icon: Building2, title: 'Company Intelligence', desc: 'Deep-dive company profiles with interview patterns, tech stacks, and frequent topics.', color: 'var(--accent-orange)' },
  { icon: BarChart3, title: 'Performance Analytics', desc: 'Track your progress over time with detailed charts, topic scores, and readiness trends.', color: '#f472b6' },
];

const steps = [
  { num: '01', title: 'Upload Your Resume', desc: 'Upload your PDF resume. AI extracts and analyzes all key information.' },
  { num: '02', title: 'Add Job Description', desc: 'Paste or upload the JD. Get instant ATS score and skill gap analysis.' },
  { num: '03', title: 'Start Interview', desc: 'Choose your mode: timed, company-specific, or practice. Questions are personalized to you.' },
  { num: '04', title: 'Get Feedback', desc: 'AI evaluates every answer with scores, improved answers, and a study plan.' },
];

const testimonials = [
  { name: 'Priya Sharma', role: 'Got hired at JPMorgan', text: 'The company-specific questions were incredibly accurate. I saw the same SQL optimization questions in my actual interview!', rating: 5 },
  { name: 'Rahul Verma', role: 'SDE at Amazon', text: 'My ATS score went from 42% to 87% after following the skill gap roadmap. Total game changer.', rating: 5 },
  { name: 'Ananya Singh', role: 'Data Engineer at Microsoft', text: 'The AI feedback on my answers was more detailed than any mock interview coach I\'ve tried.', rating: 5 },
];

const faqs = [
  { q: 'How are the interview questions personalized?', a: 'Questions are generated by Gemini AI using your actual resume projects, target role, company, and the job description. Each interview is unique to you.' },
  { q: 'How accurate is the ATS score?', a: 'Our ATS engine uses AI to compare skills, keywords, and experience alignment — giving you a realistic match score similar to what real ATS systems use.' },
  { q: 'Can I use this without a job description?', a: 'Yes! You can take interviews in practice mode with just your resume, or specify a role/company without uploading a JD.' },
  { q: 'Is my data secure?', a: 'All data is encrypted in transit and at rest. Your resume and interview data are only accessible to your account.' },
];

export default function Landing() {
  return (
    <div style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)', minHeight: '100vh' }}>
      {/* Background blobs */}
      <div className="bg-blob" style={{ width: 600, height: 600, background: '#6366f1', top: -200, left: -200 }} />
      <div className="bg-blob" style={{ width: 500, height: 500, background: '#8b5cf6', top: 200, right: -150 }} />

      {/* Navbar */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 50,
        padding: '16px 48px',
        background: 'rgba(10,10,15,0.8)',
        borderBottom: '1px solid var(--border)',
        backdropFilter: 'blur(20px)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: 'var(--gradient-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Zap size={18} color="white" />
          </div>
          <span style={{ fontFamily: 'Outfit', fontWeight: 800, fontSize: '1.2rem' }}>InterviewAI</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Link to="/login" className="btn-ghost">Sign In</Link>
          <Link to="/register" className="btn-primary" style={{ padding: '10px 24px' }}>Get Started Free</Link>
        </div>
      </nav>

      {/* Hero */}
      <section style={{ padding: '160px 48px 80px', textAlign: 'center', position: 'relative', zIndex: 1 }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8, padding: '6px 16px',
          background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)',
          borderRadius: 20, marginBottom: 24, fontSize: '0.85rem', color: '#818cf8'
        }}>
          <Zap size={14} /> Powered by Google Gemini AI
        </div>

        <h1 style={{ fontSize: 'clamp(2.5rem, 6vw, 4.5rem)', fontWeight: 900, lineHeight: 1.1, marginBottom: 24, maxWidth: 900, margin: '0 auto 24px' }}>
          Ace Every Interview with
          <br />
          <span className="gradient-text">AI-Powered Preparation</span>
        </h1>

        <p style={{ fontSize: '1.2rem', color: 'var(--text-secondary)', maxWidth: 600, margin: '0 auto 40px', lineHeight: 1.7 }}>
          Upload your resume, paste a job description, and get personalized mock interviews, ATS scores, skill gap analysis, and AI feedback — all in one platform.
        </p>

        <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link to="/register" className="btn-primary" style={{ fontSize: '1.05rem', padding: '14px 36px' }}>
            Start For Free <ChevronRight size={18} />
          </Link>
          <Link to="/login" className="btn-secondary" style={{ fontSize: '1.05rem', padding: '14px 36px' }}>
            Sign In
          </Link>
        </div>

        <div style={{ display: 'flex', gap: 32, justifyContent: 'center', marginTop: 48, color: 'var(--text-muted)', fontSize: '0.875rem', flexWrap: 'wrap' }}>
          {['No credit card required', 'Resume parsing in seconds', 'Personalized to your profile'].map(t => (
            <div key={t} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <CheckCircle size={16} color="var(--accent-green)" /> {t}
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section style={{ padding: '80px 48px', position: 'relative', zIndex: 1 }}>
        <div style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', marginBottom: 16 }}>Everything You Need to Land the Job</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>One platform. Every tool you need for interview success.</p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24, maxWidth: 1100, margin: '0 auto' }}>
          {features.map(({ icon: Icon, title, desc, color }) => (
            <div key={title} className="glass-card" style={{ padding: 28 }}>
              <div style={{ width: 48, height: 48, borderRadius: 12, background: `${color}20`, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16 }}>
                <Icon size={22} color={color} />
              </div>
              <h3 style={{ fontSize: '1.1rem', marginBottom: 10 }}>{title}</h3>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: '0.95rem' }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section style={{ padding: '80px 48px', position: 'relative', zIndex: 1 }}>
        <div style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', marginBottom: 16 }}>How It Works</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>From zero to interview-ready in 4 simple steps.</p>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 24, maxWidth: 1000, margin: '0 auto' }}>
          {steps.map(({ num, title, desc }) => (
            <div key={num} style={{ textAlign: 'center', padding: 28 }}>
              <div style={{
                width: 56, height: 56, borderRadius: '50%', margin: '0 auto 20px',
                background: 'var(--gradient-primary)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontFamily: 'Outfit', fontWeight: 800, fontSize: '1.1rem', color: 'white'
              }}>{num}</div>
              <h3 style={{ marginBottom: 10 }}>{title}</h3>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: '0.95rem' }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Testimonials */}
      <section style={{ padding: '80px 48px', position: 'relative', zIndex: 1 }}>
        <div style={{ textAlign: 'center', marginBottom: 56 }}>
          <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', marginBottom: 16 }}>Loved by Candidates</h2>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24, maxWidth: 1000, margin: '0 auto' }}>
          {testimonials.map(({ name, role, text, rating }) => (
            <div key={name} className="glass-card" style={{ padding: 28 }}>
              <div style={{ display: 'flex', gap: 4, marginBottom: 16 }}>
                {Array.from({ length: rating }).map((_, i) => (
                  <Star key={i} size={16} fill="var(--accent-orange)" color="var(--accent-orange)" />
                ))}
              </div>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 20, fontStyle: 'italic' }}>"{text}"</p>
              <div>
                <div style={{ fontWeight: 600 }}>{name}</div>
                <div style={{ fontSize: '0.85rem', color: 'var(--accent-green)' }}>{role}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section style={{ padding: '80px 48px', position: 'relative', zIndex: 1, maxWidth: 800, margin: '0 auto' }}>
        <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', textAlign: 'center', marginBottom: 48 }}>Frequently Asked Questions</h2>
        {faqs.map(({ q, a }) => (
          <div key={q} style={{ padding: '24px 0', borderBottom: '1px solid var(--border)' }}>
            <h4 style={{ marginBottom: 10, fontSize: '1rem' }}>{q}</h4>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, fontSize: '0.95rem' }}>{a}</p>
          </div>
        ))}
      </section>

      {/* CTA */}
      <section style={{ padding: '80px 48px', textAlign: 'center', position: 'relative', zIndex: 1 }}>
        <div style={{
          maxWidth: 700, margin: '0 auto',
          padding: 48, borderRadius: 24,
          background: 'linear-gradient(135deg, rgba(99,102,241,0.15), rgba(139,92,246,0.15))',
          border: '1px solid rgba(99,102,241,0.25)'
        }}>
          <h2 style={{ fontSize: '2rem', marginBottom: 16 }}>Ready to Land Your Dream Job?</h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: 32, fontSize: '1.1rem' }}>
            Join thousands of candidates who improved their interview skills with InterviewAI.
          </p>
          <Link to="/register" className="btn-primary" style={{ fontSize: '1.1rem', padding: '16px 40px' }}>
            Get Started Free <ChevronRight size={20} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer style={{ padding: '32px 48px', borderTop: '1px solid var(--border)', textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.875rem' }}>
        © 2024 InterviewAI. Built with Gemini AI.
      </footer>
    </div>
  );
}
